#+title: Emacs Config

** Use Package

Install packages by default when configured with use-package.

#+begin_src emacs-lisp
(setq use-package-always-ensure t)
#+end_src

Macro to use to configure built-in features, rather than packages that do not
need to be installed.

#+begin_src emacs-lisp
(defmacro use-feature (name &rest args)
  "`use-package' with package installation (`ensure') disabled."
  (declare (indent defun))
  `(use-package ,name
     :ensure nil
     ,@args))
#+end_src

* Base Settings

** Keybindings

Use =C-j= and =M-j= as alternatives to =C-x= and =M-x= for easier home row access.

#+begin_src emacs-lisp
(global-set-key (kbd "C-j") ctl-x-map)
(global-set-key (kbd "M-j") 'execute-extended-command)
#+end_src

** Customization Saving

Do not save customizations in =init.el=, instead save them in a temporary file
that will be discarded. As a result, any customizations made in a session will
not be persisted across sessions.

#+begin_src emacs-lisp
(setq custom-file (expand-file-name
                   (format "custom-%d-%d.el" (emacs-pid) (random))
                   temporary-file-directory))
#+end_src

** No Littering

Move all common files typically written to the =user-emacs-directory= to the =var=
and =etc= subdirectories so that they can be included in =.gitignore=

#+begin_src emacs-lisp
(use-package no-littering
  :ensure (:wait t))
#+end_src

* User Interface

** Frame Size

Maximize frame on startup without using native fullscreen.

#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src

** Toolbar

#+begin_src emacs-lisp
(tool-bar-mode -1)
#+end_src

** Icons

#+begin_src emacs-lisp
(use-package nerd-icons)
#+end_src

** Mode Line

#+begin_src emacs-lisp
(use-package doom-modeline
  :hook (elpaca-after-init . doom-modeline-mode))
#+end_src

** Theme

#+begin_src emacs-lisp
(use-package github-dark-vscode-theme
  :config
  (load-theme 'github-dark-vscode t)
  ;; Remove bold weight from syntax faces to match our light font weight
  (set-face-attribute 'font-lock-keyword-face nil :weight 'light)
  (set-face-attribute 'font-lock-builtin-face nil :weight 'light)
  (set-face-attribute 'font-lock-function-name-face nil :weight 'light)
  (set-face-attribute 'font-lock-type-face nil :weight 'light)
  (set-face-attribute 'font-lock-constant-face nil :weight 'light))
#+end_src

** Font Ligatures

Enable Monaspace ligatures and texture healing via OpenType features.

#+begin_src emacs-lisp
(set-face-attribute 'default nil
                    :font (font-spec :family "Monaspace Neon"
                                     :size 16
                                     :weight 'light
                                     :width 'normal)
                    :fontset "fontset-default")
(set-fontset-font "fontset-default" 'unicode
                  (font-spec :family "Monaspace Neon") nil 'prepend)
#+end_src

#+begin_src emacs-lisp
(use-package ligature
  :config
  (ligature-set-ligatures 'prog-mode
                          '("|||>" "<|||" "<==>" "<!--" "####" "~~>" "***" "||=" "||>"
                            ":::" "::=" "=:=" "===" "==>" "=!=" "=>>" "=<<" "=/=" "!=="
                            "!!." ">=>" ">>=" ">>>" ">>-" ">->" "->>" "-->" "---" "-<<"
                            "<~~" "<~>" "<*>" "<||" "<|>" "<$>" "<==" "<=>" "<=<" "<->"
                            "<--" "<-<" "<<=" "<<-" "<<<" "<+>" "</>" "###" "#_(" "..<"
                            "..." "+++" "/==" "///" "_|_" "www" "&&" "^=" "~~" "~@" "~="
                            "~>" "~-" "**" "*>" "*/" "||" "|}" "|]" "|=" "|>" "|-" "{|"
                            "[|" "]#" "::" ":=" ":>" ":<" "$>" "==" "=>" "!=" "!!" ">:"
                            ">=" ">>" ">-" "-~" "-|" "->" "--" "-<" "<~" "<*" "<|" "<:"
                            "<$" "<=" "<>" "<-" "<<" "<+" "</" "#{" "#[" "#:" "#=" "#!"
                            "##" "#(" "#?" "#_" "%%" ".=" ".-" ".." ".?" "+>" "++" "?:"
                            "?=" "?." "??" ";;" "/*" "/=" "/>" "//" "__" "~~" "(*" "*)"
                            "\\\\" "://"))
  (global-ligature-mode t))
#+end_src

** Line Numbers

#+begin_src emacs-lisp
(global-display-line-numbers-mode 1)
#+end_src

** Tree View (Treemacs)

#+begin_src emacs-lisp
(use-package treemacs
  :bind (("C-c t" . treemacs))
  :config
  (setq treemacs-indentation 1)
  (setq treemacs-space-between-root-nodes nil)
  (set-face-attribute 'treemacs-root-face nil :height 1.0 :weight 'normal :slant 'italic))
#+end_src

** Project Management (Projectile)

#+begin_src emacs-lisp
(use-package projectile
  :config
  (projectile-mode +1))

(use-package treemacs-projectile
  :after (treemacs projectile))
#+end_src

** Completion Menu (Vertico)

#+begin_src emacs-lisp
(use-package vertico
  :init
  (vertico-mode))
#+end_src

** Consult

#+begin_src emacs-lisp
(use-package consult
  :bind (("C-x b" . consult-buffer)))
#+end_src

** Completion Style (Orderless)

The orderless completion style allows typing parts of what is being matched,
separated by spaces. For example, "som thi" will match "this-is-some-thing".

#+begin_src emacs-lisp
(use-package orderless
  :init
  (setq completion-styles '(orderless basic)
        completion-category-defaults nil
        completion-category-overrides '((file (styles partial-completion)))))
#+end_src

** Terminal (vterm)

#+begin_src emacs-lisp
(use-package vterm
  :hook (vterm-mode . (lambda ()
                        (set (make-local-variable 'buffer-face-mode-face) '(:family "JetBrainsMono Nerd Font"))
                        (buffer-face-mode t))))
#+end_src

* Org Mode

** Capture

#+begin_src emacs-lisp
(use-feature org
  :bind (("C-c c" . org-capture)
         ("C-c a" . org-agenda))
  :config
  (setq org-directory "~/org")
  (setq org-agenda-files '("~/org"))
  (setq org-default-notes-file (concat org-directory "/inbox.org"))
  (setq org-capture-templates
        '(("t" "Todo" entry (file+headline "~/org/inbox.org" "Tasks")
           "* TODO %?\n%U")
          ("n" "Note" entry (file+headline "~/org/notes.org" "Notes")
           "* %?\n%U\n%a")
          ("j" "Journal" entry (file+datetree "~/org/journal.org")
           "* %?\n%U"))))
#+end_src

* Version Control

* Magit

#+begin_src emacs-lisp
  ;; (use-package magit)
#+end_src

Install latest version of transient, as the version included in Emacs is not recent enough.

#+begin_src emacs-lisp
  ;; (use-package transient)
#+end_src


* Startup Time

#+begin_src emacs-lisp
(add-hook 'after-init-hook
          (lambda ()
            (let ((inhibit-message t))
              (message "Emacs init time: %s" (emacs-init-time)))))
#+end_src

